[project]
name = "ChatUSP"
version = "0.1.0"
description = "Chatbot da USP"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "crawl4ai>=0.4.247",
    "fastapi>=0.115.6",
    "loguru>=0.7.3",
    "pydantic-ai>=0.0.19",
]
