name: pgai
services:
  db:
    image: timescale/timescaledb-ha:pg16
    environment:
      POSTGRES_PASSWORD: password
      OPENAI_API_KEY: 
    ports:
      - "5432:5432"
    volumes:
      - pgai_data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  vectorizer-worker:
    image: timescale/pgai-vectorizer-worker:0.1.0
    environment:
      PGAI_VECTORIZER_WORKER_DB_URL: postgres://postgres:password@db:5432/postgres
      OPENAI_API_KEY: 
    depends_on:
      db:
        condition: service_healthy

volumes:
  pgai_data:
